### ISSUE TITLE
CryptographicException, the payload was invalid

### ISSUE THREAD

**Issue by mrn-aglic** [explorer14/JwtAuthenticationHelper#5] opened 2020-06-10 07:59 UTC
Hi, I followed your example for Jwt cookie authentication. However, I don't know why, but I keep getting an error CryptographicException, the payload was invalid whenever I have a cookie.

Here is my startup config.

            ```
             var appName = "app.myname";

            services.AddDataProtection(options =>
                    options.ApplicationDiscriminator =
                        appName)
                .SetApplicationName(
                    appName);
            services.AddScoped<IDataSerializer<AuthenticationTicket>, TicketSerializer>();
            
            // Konfiguriramo schemu za authentikaciju.
            services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme =
                    CookieAuthenticationDefaults.AuthenticationScheme;
                x.DefaultSignInScheme =
                    CookieAuthenticationDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme =
                    CookieAuthenticationDefaults.AuthenticationScheme;
            })
                .AddCookie(opt =>
                {
                    //opt.TicketDataFormat = JwtAuthTicketFormat.Create(validationParameters, services);
                    opt.SlidingExpiration = false;
                    opt.Cookie.Name = cookieName;
                    opt.LoginPath = "/pmfst/login";
                    opt.LogoutPath = "/pmfst/logout";
                    opt.AccessDeniedPath = "/pmfst/login";
                    opt.ReturnUrlParameter = "/";
                   
                    opt.TicketDataFormat = new JwtAuthTicketFormat( validationParameters, TicketSerializer.Default, 
                                                                                                                    
                        services.BuildServiceProvider().GetDataProtector(new[]
                        {
                            $"{appName}-Auth1"
                        }));
                });
```

On the other hand, I also keep getting a stackoverflow exception, I believe this is when I don't have a cookie.

NOTE: I don't have a path for logout, but I don't believe that is the issue.

**Comment by explorer14** [comment] 2020-06-10 11:14
hey @mrn-aglic , are you running this locally or in a deployed environment with multiple instances?

**Comment by mrn-aglic** [comment] 2020-06-10 11:43
I'm running it locally. Perhaps its related to me using .NET Core 3.1?

**Comment by explorer14** [comment] 2020-06-10 23:15
Hmm! Interesting I have been able to replicate the problem locally against a 3.1 web app! With the 2.1 reference app in the repo, it seems to work!  Let me see what's the problem here, I will let you know as soon as I have something, alternatively if you figure something out PRs are always welcome!

**Comment by explorer14** [comment] 2020-06-11 19:17
OK this is really odd! I just tried your code again (_the only thing I didn't see in your code was the `IJwtTokenGenerator` registration in the DI container so I added that  too_) in an ASP.NET Core 3.1 app and this time it worked (_and subsequent times as well actually_). Not sure what's going on on your side.

On a side note, you are already registering the `IDataSerializer` in the DI so I would recommend resolving it from the DI container itself when you pass it in during the instantiation of `JwtAuthTicketFormat`.  Although, that doesn't seem to the cause of the problem. 

Can you share your full `Startup.cs` and any login controllers that you have set up?

**Comment by mrn-aglic** [comment] 2020-06-11 21:42
Sorry for making you wait my laptop broke down the other day. 
I might not have been clear enough on my initial post... sorry about that. I was following your example, I had my own JwtService implementation for generating the token. 
I wanted to implement only the authentication ticket that would allow me to automatically decrypt a cookie (if I understood correctly what happens).

I'm gonna post all of the code that might be relevant:

Generate token:

```
       public string GenerateSecurityToken(int id, string email, string[] roles)
        {
            var roleClaims = roles.Select(r => new Claim(ClaimTypes.Role, r));
            var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, id.ToString()),
                    new Claim(ClaimTypes.Email, email)
                }
                .Concat(roleClaims);

            var symmetricKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(_secret)
            );
            var signinCredentials =
                new SigningCredentials(symmetricKey, SecurityAlgorithms.HmacSha256);

            var expirationDate = DateTime.Now.AddMinutes(_durationInMinutes);

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(claims),
                Expires = expirationDate,
                SigningCredentials = signinCredentials,
                Issuer = _issuer
            };

            var tokenHandler = new JwtSecurityTokenHandler();
            var token = tokenHandler.CreateToken(tokenDescriptor);

            return tokenHandler.WriteToken(token);
        }
```


The entire Startup class:

```
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        private void SetupDbContext(IServiceCollection services)
        {
            var connString = Configuration.GetConnectionString("pma");

            services.AddEntityFrameworkNpgsql()
                .AddDbContext<pma_pmfContext>(options => options.UseNpgsql(connString));
        }

        public void AddAuthentication(IServiceCollection services)
        {
            var config = Configuration.GetSection("jwtConfig").Get<JwtConfiguration>();
            services.AddSingleton(s => config);
            
            services.AddTransient<AuthDbContext<pma_pmfContext>>();
            services.AddIdentity<IAppUser, IAppUserRole>();
            services.AddTransient<IUserStore<IAppUser>, UserStore<pma_pmfContext>>()
                .AddTransient<IRoleStore<IAppUserRole>, UserRoleStore<pma_pmfContext>>();

            
            services.AddTransient<JwtService>();

            // Konfiguriramo schemu za authentikaciju.
            services.AddAuthentication(x =>
                {
                    x.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddCookie(opt => opt.SlidingExpiration = true)
                .AddJwtBearer(options =>
                {
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuerSigningKey = true,
                        // ključ za prijavu tokena
                        IssuerSigningKey = new SymmetricSecurityKey(
                            Encoding.UTF8.GetBytes(
                                Configuration.GetSection("jwtConfig:secret").Get<string>()
                            )
                        ),
                        RequireExpirationTime = true,
                        ValidateIssuer = true,
                        ValidIssuer = Configuration.GetSection("jwtConfig:issuer").Get<string>(),
                        ValidateAudience = false
                    };
                });
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddNewtonsoftJson();
            services.AddControllersWithViews();

            services.AddScoped<CourseRepository>();

            services.AddScoped<CourseService>();

            SetupDbContext(services);
            AddAuthentication(services);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    "PmfKolegiji",
                    "pmfst/kolegiji",
                    new {controller = "courses", action = "courses"}
                );
                endpoints.MapControllerRoute(
                    name: "PmfOdjeli",
                    pattern: "pmfst/odjeli",
                    defaults: new {controller = "pmf", action = "odjeli"}
                );
                endpoints.MapControllerRoute(
                    "pmfLogin",
                    "pmfst/login",
                    new {area = "authentication", controller = "authentication", action = "login"}
                );

                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }

```

Since my laptop broke down, and I was working on my father's for two days, I forgot to transfer the project with the latest changes, including the JwtAuthenticationTicket, whose implementation I have now lost :-( 

I've noticed that the Startup is missing all of the code that used the ticket... sorry for wasting your time, I'll try to reimplement the JwtAuthenticationTicket based on your example again.

**Comment by explorer14** [comment] 2020-06-11 22:15
Its no problem at all! I did dig a bit [deeper](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/dangerous-unprotect?view=aspnetcore-3.1) and it seems something about data [protection package](https://github.com/Azure/azure-functions-host/issues/1832) was not quite right. Something to do with protection keys having been changed since the app ran which is _probably_ why it threw the exception? The unprotecting logic also wasn't covered within the try catch block so the exception went unhandled.

Could have been breaking change in 3.1, not sure but I've pushed a [change for handling the exception](https://github.com/explorer14/JwtAuthenticationHelper/commit/dec76eddd61005794f8931254978ea120be1af97#diff-2a40d84104f2a374a527a88bde3d70ed) to this repo which seems to have resolved the problem. If you replace the implementation of `JwtAuthTicketFormat` with the updated one from the repo, it should work! I am still a bit puzzled as to why that exception happened in the first place, it never failed in 2.1! I've also updated the version of the DataProtection package. Let me know if this resolves your problem!

**Comment by mrn-aglic** [comment] 2020-06-12 17:32
Your example works for me now. I've stumbled upon something I don't understand, I hope you could answer. 
ASP.NET Core doesn't generate my cookie when I set new CookieBuilder in the example below:

```
.AddCookie(opt =>
                {
                    opt.TicketDataFormat = JwtAuthTicketFormat.Create(jwtConfig, serializer, dataProtector);
                    opt.LoginPath = "/pmfst/login";
                    opt.LogoutPath = "/pmfst/logout";
                    opt.AccessDeniedPath = "/pmfst/login";
                    opt.ReturnUrlParameter = "returnUrl";
                    opt.ExpireTimeSpan = TimeSpan.FromMinutes(20);
                    opt.Cookie.Name = ".pma.vj12.jwt.Cookie";
                    // opt.Cookie = new CookieBuilder
                    // {
                    //     Name = ".pma.vj12.Cookie",
                    //     HttpOnly = true,
                    //     Path = "/jwt",
                    //     SameSite = SameSiteMode.Lax,
                    //     SecurePolicy = CookieSecurePolicy.SameAsRequest
                    // };
                });
```

I've published the example on GitHub: https://github.com/mrn-aglic/AuthMvcDemo

**Comment by explorer14** [comment] 2020-06-12 22:12
If you set it the Path to "/" it should work because that's going to be the default base path for your app.

It relates to if you want to use the same cookie across different base paths. This [SO post](https://stackoverflow.com/questions/47296934/how-to-set-path-for-asp-net-core-identity-cookie) explains the context a little bit more and also this Microsoft docs [section](https://stackoverflow.com/questions/47296934/how-to-set-path-for-asp-net-core-identity-cookie).

[Configuring request base paths](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#deal-with-path-base-and-proxies-that-change-the-request-path) is useful if you are hosting ASP.NET Core apps behind reverse proxies because you can then re-route requests appropriately. I haven't used this part so I can only guess!

**Comment by explorer14** [comment] 2020-06-19 17:48
I am assuming this is resolved, closing it!

**Closed as completed by explorer14** 2020-06-19 17:48 UTC
